# -*- coding: utf-8 -*-
"""created combined file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zkt1qqkwLjQIjhRf8otUVDrk9lEsykjK
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/CS224N_Final_Project

import shutil
import os
import csv
import linecache
from shutil import copyfile
import ipywidgets as widgets
import numpy as np
import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt

df1 = pd.read_csv('/content/drive/MyDrive/CS224N_Final_Project/with-10.csv',sep=",")
df1.columns = ['OriginalTweet', 'Sentiment']
df1 = df1.sort_values(by=['Sentiment'])
df1.to_csv("sorted-with-10.csv")

df1 = pd.read_csv('/content/drive/MyDrive/CS224N_Final_Project/final-train.csv',sep=",")
df1.columns = ['OriginalTweet', 'Sentiment']
print(df1)
df1 = df1.dropna()
df1['Sentiment'] = df1['Sentiment'].astype(int)
print(df1)
df1.to_csv("final-train-int.csv")



