# -*- coding: utf-8 -*-
"""FOR ELYSE - twarcBIZ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KkjsR7BUdDeSJbBsHvZOBBgHb9t78qOm
"""

!pip3 install twarc

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/CS224N_Final_Project

from twarc import Twarc

consumer_key="jmcFK9uIhwd42Bw2k6TytwmZk"
consumer_secret="87rrwSUnGXGRG0OKsznPQZdzaskoNTE0rwPt9gChPRQXcUNwKj"
access_token="1500972724029558785-dEHGIyS6BD6JTh1KQ0RoNLn83qja6D"
access_token_secret="Q9gdAGT9ba1HNhJRaOs8Lqsc84mhqINuAD9ppDbJGkK4H"

import pandas as pd 


t = Twarc(consumer_key, consumer_secret, access_token, access_token_secret)

strs = []
date = []
country = []
i = 0
p = 0
for tweet in t.hydrate(open('tweets2hydrate/us-labeled-mini.csv')):
    i += 1
    if i == 10:
      break
    if tweet['place']:
        if tweet['place']['country'] == 'United States' or  tweet['place']['country'] == 'United Kingdom' or  tweet['place']['country'] == 'Canada':
          p += 1
          print(p)
          strs.append(tweet['full_text'])
          date.append(tweet['created_at'])
          country.append((tweet['place']['country']))

total = pd.DataFrame([strs, date, country])
total = pd.DataFrame.transpose(total)

#total.to_csv('hydrated-us-labeled-full.csv' , index = True)