# -*- coding: utf-8 -*-
"""training data - twarcBIZ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FvpwJR64IvCFmJngHdcBd5W_bafRZK4i
"""

!pip3 install twarc
!pip install --upgrade twarc

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/CS224N_Final_Project

from twarc import Twarc


consumer_key="ukc4AdhfcaGaDltF3tBiLi8jQ"
consumer_secret="mHpOF3VuWpCCubYlgLaWLd8wGYOu625pO5XMLHw4FXebZbcrxr"
access_token="1156238956779986947-ygcAES31ByJDSXjX9XNI4Fr94kfhUw"
access_token_secret="ckEW3z6oWa5PB9SiHjgJI2fkg9lLnGkjVwKHKxmWwTl7i"

#twarc2 configure

import pandas as pd 


t = Twarc(consumer_key, consumer_secret, access_token, access_token_secret)

strs = []
sent = []
i = 0
p = 0

#df = pd.read_csv('tweets2hydrate/corona-tweets-01.csv')
csv_dict = pd.read_csv('tweets2hydrate/corona-tweets-600.csv', header=None, index_col=0, squeeze=True).to_dict()
#print(csv_dict[1240727808340414464])

#for tweet in t.hydrate(open('tweets2hydrate/may-2020-unlabeled-full.csv')):
for tweet in t.hydrate(open('tweets2hydrate/corona-tweets-600.csv')):
    i += 1
    
    tweet_id = tweet['id']
    if i == 100:
      print(tweet)
      break
    strs.append(tweet['full_text'])
    if csv_dict[tweet_id] > 0 and csv_dict[tweet_id] <= 1: # positive sentiment
      sent.append(2)
    elif csv_dict[tweet_id] < 0 and csv_dict[tweet_id] >= -1: # negative sentiment
      sent.append(0)
    elif csv_dict[tweet_id] == 0:
      sent.append(1)
print(type(sent[1]))
total = pd.DataFrame([strs, sent])
total = pd.DataFrame.transpose(total)

total.to_csv('try.csv' , index = True)

import pandas as pd
lst_csvs = ['tweets2hydrate/tries/1.csv','tweets2hydrate/tries/2.csv', 'tweets2hydrate/tries/3.csv', 'tweets2hydrate/tries/4.csv', 'tweets2hydrate/tries/5.csv', 'tweets2hydrate/tries/6.csv', 'tweets2hydrate/tries/7.csv', 'tweets2hydrate/tries/8.csv']
lst_dfs = []
for path in lst:
  df = pd.read_csv(path)
  lst_dfs.append(df)
  
pd.concat(lst_dfs).to_csv('here.csv', index=False)

df_1 = pd.read_csv('here.csv')
df_2 = pd.read_csv('vaccine-senitment-hydrated.csv')

pd.concat([df_1, df_2]).to_csv('final-train.csv', index=False)