# -*- coding: utf-8 -*-
"""twarcBIZ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m1WkPddd7HOF-k1oM81kS0SCQ8au4x81
"""

!pip3 install twarc

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/CS224N_Final_Project

from twarc import Twarc

consumer_key="ukc4AdhfcaGaDltF3tBiLi8jQ"
consumer_secret="mHpOF3VuWpCCubYlgLaWLd8wGYOu625pO5XMLHw4FXebZbcrxr"
access_token="1156238956779986947-ygcAES31ByJDSXjX9XNI4Fr94kfhUw"
access_token_secret="ckEW3z6oWa5PB9SiHjgJI2fkg9lLnGkjVwKHKxmWwTl7i"

import pandas as pd 


t = Twarc(consumer_key, consumer_secret, access_token, access_token_secret)

strs = []
date = []
country = []

china_t = []
china_d = []
i = 0
p = 0
for tweet in t.hydrate(open('tweets2hydrate/real-world/march-2022-unlabeled-full.csv')):
    i += 1
    if i == 400000:
      break
    if tweet['place']:
        if tweet['place']['country'] == 'United States' or  tweet['place']['country'] == 'United Kingdom' or  tweet['place']['country'] == 'Canada':
          p += 1
          print(p)
          strs.append(tweet['full_text'])
          date.append(tweet['created_at'])
          country.append((tweet['place']['country']))
        if tweet['place']['country'] == 'China':
          print("china")
          china_t.append(tweet['full_text'])
          china_d.append(tweet['created_at'])


total = pd.DataFrame([strs, date, country])
total = pd.DataFrame.transpose(total)

china_total = pd.DataFrame([china_t, china_d])
china_total = pd.DataFrame.transpose(china_total)

total.to_csv('hydrated-march-2022.csv' , index = True)
china_total.to_csv('hydrated-march-2022-china.csv' , index = True)